spring:
  profiles:
    active: local

---

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


  profiles: local

  datasource:
    url: jdbc:h2:mem:ct3o3
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
        #       show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  test-3o3:
    url: "https://codetest.3o3.co.kr/"
    timeout: 25

szs:
  #회원가입 실패 후 유저가 실패를 확인 할 수 있는 시간입니다. 메일 알림 기능 대신 사용함.
  find-sign-up-event-seconds: 600



encryption:
  key:
    member-regno: "iwanttogetin3o3heworlddd34567890"
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace